version: '3.1'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - var.env
    volumes:
      - ./:/code
    ports:
      - "8000:8000"
  mercure:
    image: dunglas/mercure
    env_file:
      - var.env
    ports:
      - "3000:80"