# Generated by Django 2.2.1 on 2019-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
