# Generated by Django 2.2.1 on 2019-05-04 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=models.SET(None), to=settings.AUTH_USER_MODEL),
        ),
    ]
